### ISSUE TITLE
No heat production bug

### ISSUE THREAD

**Issue by kacperholak** [nwai90/terraforming-mars#55]
It looks like no heat production bonus is given when reaching -24 C.

id=p313656df5478 - when playing prelude
id=pf13f097eaaed - when playing Deimos

**Comment by nwai90** [comment]
Will look. This issue could not be reproduced in a new game so far.

**Comment by buko1234** [comment]
id=gb9f0788ad924
Repeated again. 

From logs:
Generation 1
glupti92 played Cheung Shing MARS
glupti92 kept 7 project cards
SzyBek45 played Valley Trust
SzyBek45 kept 6 project cards
glupti92 played Smelting Plant
glupti92 played Self-Sufficient Settlement
glupti92 placed city tile on row 5 position 6
glupti92's plants amount increased by 3
SzyBek45 played UNMI Contractor
SzyBek45 drew 1 card(s)
SzyBek45 played Great Aquifer
SzyBek45 placed ocean tile on row 4 position 4
SzyBek45's plants amount increased by 2
SzyBek45 placed ocean tile on row 5 position 4
SzyBek45's plants amount increased by 2
glupti92 played Deep Well Heating
glupti92 played Fuel Factory
SzyBek45 played Research Network
SzyBek45 drew 3 card(s)
SzyBek45 played Space Hotels
glupti92 passed
SzyBek45 played Cartel
SzyBek45's megacredits production increased by 5
SzyBek45 passed
Generation 2
glupti92 bought 2 card(s)
SzyBek45 bought 2 card(s)
SzyBek45 claimed Specialist milestone
SzyBek45 played Invention Contest
SzyBek45 drew 1 card(s)
glupti92 played Big Asteroid                 <- this should increase heat production
SzyBek45's plants amount decreased by 4 by glupti92
glupti92 played SF Memorial

**Comment by nwai90** [comment]
Issue resolved thanks to @buko1234. This problem happens for games that are using outdated JSON files to upload in the Create Game page. The JSON files need to be updated by adding a new line:

```
"automaSoloVariant": false,
```
